core/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'core.views.index', name='index'),
    url(r'^home/$', 'core.views.home', name='home'),
    url(r'^profile/$', 'core.views.profile', name='profile'),
    url(r'^about/$', 'core.views.about', name='about'),
    url(r'^invite/team/members/$', 'core.views.invite_team_members', name='invite_team_members'),
    url(r'^mark/paid/(?P<payment_id>\d+)/$', 'core.views.mark_paid', name='mark_paid'),
    url(r'^payments/$', 'core.views.payments', name='payments'),
    url(r'^expense/add/$', 'core.views.add_expense', name='add_expense'),
    url(r'^change/group/name/(?P<group_id>\d+)/$', 'core.views.change_group_name', name='change_group_name'),
)

expense/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
  # Examples:
  url(r'^$', 'expense.views.index', name='index'),
  url(r'^add/$', 'expense.views.add_expense', name='add_expense'),
  url(r'^contributor/mixin/add/$', 'expense.views.add_contributor_mixin', name='add_contributor_mixin'),
  url(r'^contributions/$', 'expense.views.contributions', name='contributions'),
  url(r'^requested/contributions/$', 'expense.views.requested_contributions', name='requested_contributions'),
  url(r'^teammembers/add/$', 'expense.views.add_teammembers', name='add_teammembers'),
  url(r'^teammember/mixin/add/$', 'expense.views.add_teammember_mixin', name='add_teammember_mixin'),
  url(r'^bankcard/add/$', 'expense.views.add_bank_card', name='add_bank_card'),
  url(r'^multiple/add/$', 'expense.views.add_multiple_expenses', name='add_multiple_expenses'),
  url(r'^contribute/(?P<contribution_id>\d+)/$', 'expense.views.contribute_to_contribution', name='contribute_to_contribution'),
  url(r'^decline/(?P<contribution_id>\d+)/$', 'expense.views.decline_contribution', name='decline_contribution'),
)

familybridge/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.contrib import admin
from core.forms import TopLoginForm, FrontSignUpForm

admin.autodiscover()

urlpatterns = patterns('',
  # Examples:
  #url(r'^account/password_reset/', 'django.contrib.auth.views.password_reset', {'html_email_template_name': 'registration/password_reset_html_email.html'}),
  url(r'^account/', include('django.contrib.auth.urls')),
  url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'core/index.html',
                                                      'authentication_form': TopLoginForm,
                                                      'extra_context': {'signup_form': FrontSignUpForm()}
                                                      }, name='login'),
  url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout'),
  url(r'^signup/$', 'core.views.sign_up', name='signup'),
  # url(r'^blog/', include('blog.urls')),

  url(r'^admin/', include(admin.site.urls)),

  url(r'^mobile/', include('mobile.urls', namespace='mobile')),
  url(r'^expense/', include('expense.urls', namespace='expense')),
  url(r'^settings/', include('setup.urls', namespace='setup')),
  url(r'^support/', include('support.urls', namespace='support')),
  url(r'^', include('core.urls', namespace='core')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + staticfiles_urlpatterns()

core/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin, Group
from sorl.thumbnail import ImageField
import random


class EmailUserManager(BaseUserManager):

  def create_user(self, email, password=None):

    if not email:
      raise ValueError('Users must have an email address')

    user = self.model(email=email.lower())

    user.set_password(password)
    user.save(using=self._db)
    return user

  def create_superuser(self, email, password):
    user = self.create_user(email, password=password)
    user.is_staff = True
    user.is_active = True
    user.is_superuser = True
    user.save(using=self._db)
    return user


class EmailUser(AbstractBaseUser, PermissionsMixin):
  email = models.EmailField(
    verbose_name='email address',
    max_length=255,
    unique=True,
    db_index=True
  )
  first_name = models.CharField(max_length=36, blank=True, null=True)
  last_name = models.CharField(max_length=36, blank=True, null=True)
  date_of_birth = models.DateField(blank=True, null=True)
  is_active = models.BooleanField(default=True)
  is_staff = models.BooleanField(default=False)
  pic = ImageField(upload_to='profile/pics/')

  background_color = models.CharField(max_length=7, blank=True, null=True) 

  date_joined = models.DateTimeField(auto_now_add=True)

  USER_ROLE_CHOICES = (
    (0, 'Owner'),
    (1, 'Member'),
  )

  role = models.IntegerField(choices=USER_ROLE_CHOICES, default=0)
  member_groups = models.ManyToManyField(Group, related_name="group_members")
  email_verified = models.BooleanField(default=False) 

  objects = EmailUserManager()
  USERNAME_FIELD = 'email'

  @property
  def first_name_initial(self):
    return self.first_name[:1] if self.first_name else '?'

  def get_background_color(self):
    if self.background_color:
      return self.background_color
    else:
      r = lambda: random.randint(0, 255)
      self.background_color = "#%02X%02X%02X" % (r(), r(), r())
      self.save()

    return self.background_color

  def get_full_name(self):
    return '{0} {1}'.format(self.first_name, self.last_name)

  def get_short_name(self):
    return self.first_name

  def __unicode__(self):
    if self.first_name:
      return self.first_name
    else:
      return self.email

expense/models.py
from django.db import models
from django.conf import settings


class Expense(models.Model):
  owner = models.ForeignKey(settings.AUTH_USER_MODEL)
  title = models.CharField(max_length=64)
  description = models.CharField(max_length=256, blank=True, null=True)
  amount = models.DecimalField(max_digits=16, decimal_places=2)

  CATEGORY_CHOICES = (
    (0, 'Living Expense'),
    (1, 'Housing'),
    (2, 'Food'),
    (3, 'Medication'),
    (4, 'Health'),
    (5, 'Recreation'),
    (6, 'Other'),
  )

  category = models.IntegerField(choices=CATEGORY_CHOICES)
  date = models.DateField()
  contribution_requested = models.BooleanField(default=False)

  timestamp = models.DateTimeField(auto_now_add=True)  
  updated = models.DateTimeField(auto_now=True)

  def contributors(self):
    return self.contribution_set.all()


class Contribution(models.Model):
  contributor = models.ForeignKey(settings.AUTH_USER_MODEL)
  expense = models.ForeignKey(Expense)
  percentage = models.IntegerField(default=0)
  # for easy calculation without joining
  amount = models.DecimalField(max_digits=16, decimal_places=2)

  # if the user confirmed contribution
  contributed = models.DateTimeField(blank=True, null=True)
  # if the user was reminded to contribute
  last_reminded = models.DateTimeField(blank=True, null=True)
  # if payment has been fully reconciled
  reconciled = models.DateTimeField(blank=True, null=True)

  timestamp = models.DateTimeField(auto_now_add=True)  
  updated = models.DateTimeField(auto_now=True)

  def update_contribution(self):
    self.amount = self.expense.amount * float(percentage) / 100.0
    self.save()

  def feed_str(self):
    owner = self.expense.owner
    amount = self.expense.amount
    title = self.expense.title
    feed_str = "{0} spent ${1} on {2}.".format(owner.first_name, amount, title)
    return feed_str

  def contribute_str(self):
    contribute_str = "Contribute ${0} ({1}%)".format(self.amount, self.percentage)
    return contribute_str

  def contributed_exists(self):
    return self.expense.contribution_set.filter(contributed__isnull=False).exists()

  def contributed_users(self):
    return self.expense.contribution_set.filter(contributed__isnull=False)

  def requested_exists(self):
    return self.expense.contribution_set.filter(contributed__isnull=True).exists()

  def requested_users(self):
    """
      People who have been requested but not yet contributed
    """
    return self.expense.contribution_set.filter(contributed__isnull=True)

core/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from core.models import EmailUser
from django.contrib.auth.forms import AuthenticationForm


class UserCreationForm(forms.ModelForm):
  """A form for creating new users. Includes all the required
  fields, plus a repeated password."""
  password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
  password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

  class Meta:
    model = EmailUser
    fields = ('email', 'first_name', 'last_name')

  def clean_password2(self):
    # Check that the two password entries match
    password1 = self.cleaned_data.get("password1")
    password2 = self.cleaned_data.get("password2")
    if password1 and password2 and password1 != password2:
      raise forms.ValidationError("Passwords don't match")
    return password2

  def save(self, commit=True):
    # Save the provided password in hashed format
    user = super(UserCreationForm, self).save(commit=False)
    user.set_password(self.cleaned_data["password1"])
    if commit:
      user.save()
    return user


class UserChangeForm(forms.ModelForm):
  """A form for updating users. Includes all the fields on
  the user, but replaces the password field with admin's
  password hash display field.
  """
  #password = ReadOnlyPasswordHashField()

  class Meta:
    model = EmailUser
    fields = ['email', 'password', 'date_of_birth', 'is_active', 'is_staff', 'is_superuser']

  def save(self, force_insert=False, force_update=False, commit=True):
    m = super(UserChangeForm, self).save(commit=False)
    m.set_password(self.cleaned_data["password"])
    if commit:
      m.save()
    return m

  def clean_password(self):
    # Regardless of what the user provides, return the initial value.
    # This is done here, rather than on the field, because the
    # field does not have access to the initial value
    return self.cleaned_data["password"]


class TopLoginForm(AuthenticationForm):

  def __init__(self, *args, **kwargs):
    super(TopLoginForm, self).__init__(*args, **kwargs)
    login_field_width = 200

    self.fields['username'].widget.attrs['class'] = 'form-control input-lg'
    self.fields['username'].widget.attrs['style'] = 'width:%dpx;' % login_field_width
    self.fields['username'].widget.attrs['placeholder'] = 'E-mail'
    self.fields['password'].widget.attrs['class'] = 'form-control input-lg'
    self.fields['password'].widget.attrs['style'] = 'width:%dpx;' % login_field_width
    self.fields['password'].widget.attrs['placeholder'] = 'Password'


class FrontSignUpForm(UserCreationForm):

  def __init__(self, *args, **kwargs):
    super(FrontSignUpForm, self).__init__(*args, **kwargs)

    signup_field_width = 370

    self.fields['first_name'].widget.attrs['class'] = 'form-control input-lg'
    #self.fields['first_name'].widget.attrs['style'] = 'width:%dpx;' % (signup_field_width/2)
    self.fields['first_name'].widget.attrs['placeholder'] = 'First Name'
    self.fields['last_name'].widget.attrs['class'] = 'form-control input-lg'
    #self.fields['last_name'].widget.attrs['style'] = 'width:%dpx;' % (signup_field_width/2)
    self.fields['last_name'].widget.attrs['placeholder'] = 'Last Name'
    self.fields['email'].widget.attrs['class'] = 'form-control input-lg'
    #self.fields['email'].widget.attrs['style'] = 'width:%dpx;' % signup_field_width
    self.fields['email'].widget.attrs['placeholder'] = 'E-mail'
    self.fields['password1'].widget.attrs['class'] = 'form-control input-lg'
    #self.fields['password1'].widget.attrs['style'] = 'width:%dpx;' % signup_field_width
    self.fields['password1'].widget.attrs['placeholder'] = 'Password'
    self.fields['password2'].widget.attrs['class'] = 'form-control input-lg'
    #self.fields['password2'].widget.attrs['style'] = 'width:%dpx;' % signup_field_width
    self.fields['password2'].widget.attrs['placeholder'] = 'Re-type Password'

core/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, Http404
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from django.contrib import messages
from django.forms.formsets import formset_factory

from expense.models import Expense, Contribution
from core.forms import TopLoginForm, FrontSignUpForm
from expense.forms import AddExpenseForm, AddContributorForm 


def index(request):

  data = {}

  if request.user.is_authenticated():
    return HttpResponseRedirect(reverse('core:home'))

  auth_form = TopLoginForm()
  data["form"] = auth_form

  signup_form = FrontSignUpForm()
  data["signup_form"] = signup_form

  data["next"] = reverse("core:home")
  return render(request, "core/index.html", data)


def sign_up(request):

  data = {}

  # login and redirect to homepage
  signup_form = FrontSignUpForm(request.POST or None)
  if signup_form.is_valid():
    signup_form.save()
    user = authenticate(username=signup_form.cleaned_data['email'], password=signup_form.cleaned_data['password1'])
    login(request, user)

    # create a default group
    import uuid
    random_str = str(uuid.uuid4())
    default_group = Group(name="cg_{0}_{1}_{2}".format(user.first_name, user.last_name, random_str ))
    default_group.save()
    user.groups.add(default_group)
    return HttpResponseRedirect(reverse('core:home'))

  # if didn't login, return error
  auth_form = TopLoginForm()
  data["form"] = auth_form
  data["signup_form"] = signup_form
  data["next"] = reverse("core:home")
  return render(request, "core/index.html", data)


@login_required
def home(request, group_id=None):
  """
    Show dashboard of a particular care group with group_id or default group
  """
  data = {}

  data["current_page"] = "home"

  u = request.user

  # displays dashboard
  active_group = None
  group_owner = False
  if group_id:
    active_group = Group.objects.get(id=group_id)
    group_owner = True if active_group in u.groups.all() else False
    if not group_owner:
      # check if you are a member of the group or not
      if active_group not in u.member_groups.all():
        raise Http404 
  else:
    active_group = u.groups.all()[0] if u.groups.all().exists() else None
    if active_group:
      group_owner = True
    else:
      # there's no owned group so it will display a group they are member of
      active_group = u.member_groups.all()[0]
      group_owner = False
  data["group_owner"] = group_owner
  data["active_group"] = active_group

  add_expense_form = AddExpenseForm()

  data["add_expense_form"] = add_expense_form
  data["total_expense"] = 0

  AddContributorsFormset = formset_factory(AddContributorForm, can_delete=True)
  data["contributors_formset"] = AddContributorsFormset()

  data["recent_requests"] = Contribution.objects.filter(contributor=u)

  return render(request, "core/home.html", data)

@login_required
def invite_team_members(request):
  """
    Display a form to invite team members
    List of first name, last name, email, phone (optional)

    TODO: use formsets

    When submitted successfully, it adds a message and go to dashboard
  """

  data = {}

  list_of_invitees = "hello@example.com"

  messages.success("Successfully invited %s" % list_of_invitees)

  return render(request, "core/invite_team_members.html", data)

@login_required
def add_expense(request):
  """
    Shows form to add expense, upload receipt

    Saves expense and redirects to the history page
  """

  data = {}



  return render(request, "core/add_expense.html", data)

@login_required
def payments(request):
  """
    Show list of payments that one owes and list of payments that one has received

    It should also show any payments one has made
  """

  data = {}

  return render(request, "core/payments.html", data)

@login_required
def mark_paid(request, payment_id):
  """
    After a user has paid their team member, they click confirm/log payment  
  """

  data = {}

  # need to verify this is something that they owe

  return render(request, "core/payments.html", data)


@login_required
def profile(request):

  data = {}

  return render(request, "core/profile.html", data)

@login_required
def change_group_name(request, group_id):

  data = {}
  u = request.user

  if u.groups.filter(id=group_id).exists():
    # user is owner to modify the group
    g = Group.objects.get(id=group_id)

    g.name = request.POST['group_name']
    g.save()

  return render(request, "core/home.html", data)

def about(request):

  data = {}

  data["current_page"] = "about"

  return render(request, "core/about.html", data)

core/templates/core/about.html
{% extends "core/base.html" %}

{% load staticfiles %}

{% block title %}
About Us
{% endblock %}

{% block content %}

  This is about Family Bridge
{% endblock %}

core/templates/core/home.html
{% extends "core/base.html" %}

{% load staticfiles %}
{% load add_class %}

{% block title %}
Family Bridge Home
{% endblock %}

{% block additional_styles %}
  <style type="text/css">
    .slice text {
        font-size: 16pt;
        font-family: Arial;
    }   
  </style>
{% endblock %}

{% block content %}

  <!-- 
  {% if user.is_authenticated %}
    {{ user.email }} is logged in
  {% endif %}

  <p>
  {% if group_owner %}
    Currently managing care group for: {{ active_group }}
  {% else %}
    Currently accessing care group for: {{ active_group }}
  {% endif %}
  </p>
  -->

  <div class="col-sm-3 col-lg-3">
    <a href="{% url 'expense:add_teammembers' %}" class="btn btn-info btn-lg btn-block">Add Contributors</a>
    <a href="{% url 'expense:add_bank_card' %}" class="btn btn-success btn-lg btn-block">Add Bank Card</a>
    <a href="{% url 'expense:add_multiple_expenses' %}" class="btn btn-success btn-lg btn-block">Multiple Expenses</a>
      <div class="add-expense-form">
      <!-- add expense form -->
      <form action="{% url 'expense:add_expense' %}" method="POST" role="form">
        {% csrf_token %}
        <h4>Add Expense</h4>
        <div class="form-group">
          <input class="form-control" id="id_date" name="date" type="date">
        </div>
         <div class="form-group">
          <div class="row">
            <div class="reduce-right-padding-0 col-sm-9 col-lg-9">
              {{ add_expense_form.amount }}
            </div>
            <div class="reduce-left-padding-0 reduce-right-padding-0 align-right col-sm-2 col-lg-2">
              <button class="btn btn-default"><i class="icon-paper-clip"></i></button>
            </div>
          </div>
        </div>       
        <div class="form-group">
          {{ add_expense_form.title }}
        </div>
        <div class="form-group">
          {{ add_expense_form.description }}
        </div>
        <div class="form-group">
          {{ add_expense_form.category }}
        </div>

        {{ contributors_formset.management_form }}
        <div id="contributor-list">
          {% for add_contributor_form in contributors_formset %}
            {{ add_contributor_form.id }}
            <div class="form-group">
              <div class="row">
                <div class="reduce-right-padding-0 col-sm-5 col-lg-5">
                  {{ add_contributor_form.contributor }}
                </div>
                {% if contributors_formset.can_delete %}
                  <div class="reduce-left-padding-10 reduce-right-padding-0 col-sm-5 col-lg-5">
                    {{ add_contributor_form.percentage }}
                  </div>
                  <div class="reduce-left-padding-10 col-sm-1 col-lg-1">
                    <i class="icon-remove icon-2x"></i>
                  </div>
                {% else %}
                  <div class="reduce-left-padding-10 col-sm-6 col-lg-6">
                    {{ add_contributor_form.percentage }}
                  </div>
                {% endif %}
              </div>
            </div>
          {% endfor %}
        </div>

        <div class="form-group">
        <button type="button" id="add-contributor" class="btn btn-default btn-block"><i class="glyphicon glyphicon-plus"></i> Add Contributor</button>
        </div>
        <div class="form-group">
          <center>
            <input type="submit" class="btn btn-success" name="expense_submit" value="Submit">
          </center>
        </div>
      </form>
      </div>
  </div>

  <div class="col-sm-4 col-lg-4">
    <div class="recent-requests grey-area">
      <h4>Recent Requests</h4>
      {% if recent_requests %}
        {% for req in recent_requests %}
          <div class="feed-item">
            <div class="feed-content">
              {{ req.feed_str }}
            </div>
            <div class="contribute-content">
              {{ req.contribute_str }}
            </div>
            <div class="feed-actions">
              <i class="icon-comments"></i>
              <i class="icon-remove"></i>
            </div>
            <div class="feed-contribute">
              <button class="btn btn-warning">Contribute</button>
            </div>
          </div>
        {% endfor %}
      {% else %}
      There are no recent requests.
      {% endif %}
    </div>
  </div>

  <div class="col-sm-5 col-lg-5">
    <div class="expense-chart grey-area">
      <h4>Summary</h4>
      <div class="row">
        <div class="col-sm-6 col-lg-6">
          <div class="form-group">
            <select class="form-control input-lg">
              <option value="Everybody" selected>Everybody</option>
              <option value="Pam">Pam</option>
              <option value="Scott">Scott</option>
              <option value="Tom">Tom</option>
            </select>
          </div>
        </div>

        <div class="col-sm-1 col-lg-1">by</div>

        <div class="col-sm-5 col-lg-5">
          <div class="form-group">
            <select class="form-control input-lg">
              <option value="Category" selected>Category</option>
              <option value="Admin">Admin</option>
              <option value="Household">Household</option>
              <option value="Lving">Living</option>
            </select>
          </div>
        </div>
      </div>  <!-- row -->

      <div id="piechart">
      </div>
      <div id="piechart-legend">
      </div>

      <div class="row">
        <div class="total-expense-summary">
          You have spent a total of
          <div class="total-expense-cost">
            ${{ total_expense }} 
          </div>
        </div>
      </div>
    </div>
  </div>
  
{% endblock %}

{% block additional_scripts %}
  <script type="text/javascript" src="{% static "d3/d3.min.js" %}"></script>

  <script type="text/javascript">

  var w = 300,                        //width
  h = 400,                            //height
  r = 150,                            //radius
  color = d3.scale.category20c();     //builtin range of colors

  data = [{"label":"one", "value":20}, 
          {"label":"two", "value":50}, 
          {"label":"three", "value":30}];
  
  var vis = d3.select("#piechart")
      .append("svg:svg")              //create the SVG element inside the <body>
      .data([data])                   //associate our data with the document
          .attr("width", w)           //set the width and height of our visualization (these will be attributes of the <svg> tag
          .attr("height", h)
      .append("svg:g")                //make a group to hold our pie chart
          .attr("transform", "translate(" + r + "," + r + ")")    //move the center of the pie chart from 0, 0 to radius, radius

  var arc = d3.svg.arc()              //this will create <path> elements for us using arc data
      .outerRadius(r);

  var pie = d3.layout.pie()           //this will create arc data for us given a list of values
      .value(function(d) { return d.value; });    //we must tell it out to access the value of each element in our data array

  var arcs = vis.selectAll("g.slice")     //this selects all <g> elements with class slice (there aren't any yet)
      .data(pie)                          //associate the generated pie data (an array of arcs, each having startAngle, endAngle and value properties) 
      .enter()                            //this will create <g> elements for every "extra" data element that should be associated with a selection. The result is creating a <g> for every object in the data array
          .append("svg:g")                //create a group to hold each slice (we will have a <path> and a <text> element associated with each slice)
              .attr("class", "slice");    //allow us to style things in the slices (like text)

      arcs.append("svg:path")
              .attr("fill", function(d, i) { return color(i); } ) //set the color for each slice to be chosen from the color function defined above
              .attr("d", arc);                                    //this creates the actual SVG path using the associated data (pie) with the arc drawing function

      arcs.append("svg:text")                                     //add a label to each slice
              .attr("transform", function(d) {                    //set the label's origin to the center of the arc
              //we have to make sure to set these before calling arc.centroid
              d.innerRadius = 0;
              d.outerRadius = r;
              return "translate(" + arc.centroid(d) + ")";        //this gives us a pair of coordinates like [50, 50]
          })
          .attr("text-anchor", "middle")                          //center the text on it's origin
          .text(function(d, i) { return data[i].label; });        //get the label from our original data array
      
  var color_hash = {  0 : ["one", "green"],
            1 : ["two", "orange"],
            2 : ["three", "red"]
          }   

 var w = 300;
 var h = 50;

    
  var now = d3.time.hour.utc(new Date);
  var dataset = [
      [ 
          {x: d3.time.hour.utc.offset(now, -5), y: 0}, 
          {x: d3.time.hour.utc.offset(now, -4), y: 0}, 
          {x: d3.time.hour.utc.offset(now, -3), y: 2}, 
          {x: d3.time.hour.utc.offset(now, -2), y: 0}, 
          {x: d3.time.hour.utc.offset(now, -1), y: 0}, 
          {x: now, y: 0}
      ],
      [
          {x: d3.time.hour.utc.offset(now, -5), y: 3}, 
          {x: d3.time.hour.utc.offset(now, -4), y: 1}, 
          {x: d3.time.hour.utc.offset(now, -3), y: 3}, 
          {x: d3.time.hour.utc.offset(now, -2), y: 1}, 
          {x: d3.time.hour.utc.offset(now, -1), y: 5}, 
          {x: now, y: 1}
      ],
      [
          {x: d3.time.hour.utc.offset(now, -5), y: 2}, 
          {x: d3.time.hour.utc.offset(now, -4), y: 4}, 
          {x: d3.time.hour.utc.offset(now, -3), y: 1}, 
          {x: d3.time.hour.utc.offset(now, -2), y: 2}, 
          {x: d3.time.hour.utc.offset(now, -1), y: 3}, 
          {x: now, y: 1}
      ]
  ];
// add legend   

var legend = d3.select("#piechart-legend")
      .append("svg:svg").attr("height", 100).attr("width", 300).append("g")
  .attr("class", "legend")
  .attr("x", 25)
  .attr("y", h-25)
  .attr("height", 25)
  .attr("width", 300);

legend.selectAll('g').data(dataset)
    .enter()
    .append('g')
    .each(function(d, i) {
      var g = d3.select(this);
      g.append("rect")
        .attr("x", i * 70)
        .attr("y", h-25)
        .attr("width", 10)
        .attr("height", 10)
        .style("fill", color_hash[String(i)][1]);
      
      g.append("text")
        .attr("x", i * 70 + 20)
        .attr("y", h - 15)
        .attr("height",30)
        .attr("width",100)
        .style("fill", color_hash[String(i)][1])
        .text(color_hash[String(i)][0]);

    });


    // for handling additional contributors, allow adding contributor up to number
    // of members in the group
    $("#add-contributor").click(function () {
      var total_forms = parseInt($("#id_form-TOTAL_FORMS").attr('value'));
      $("#id_form-TOTAL_FORMS").attr('value', total_forms+1);
      // add new forms
      $.get("{% url 'expense:add_contributor_mixin' %}", {new_form_id: total_forms}, function (data) {
        if (data["result"] == 1) {
          $("#contributor-list").append(data['contributor_form']);
        } else {
          return false;
        }
      });
      return false;
    });

  </script>
{% endblock %}

{% block footer %}
{% endblock %}

core/templates/core/icons.html
      <ul>
        <li><i class="icon-krw icon-4x"></i> icon-krw </li>
        <li><i class="icon-large icon-comment"></i> icon-commet </li>
        <li><i class="glyphicon glyphicon-glass"></i> glyphicon-glass </li>
      </ul>

core/templates/core/login.html
{% extends "core/base.html" %}


{% block content %}
  {% if form.errors %}
  <p>Your username and password didn't match. Please try again.</p>
  {% endif %}

  <form method="POST" action="{% url 'django.contrib.auth.views.login' %}">
    {% csrf_token %}
    <table>
    <tr>
        <td>{{ form.username.label_tag }}</td>
        <td>{{ form.username }}</td>
    </tr>
    <tr>
        <td>{{ form.password.label_tag }}</td>
        <td>{{ form.password }}</td>
    </tr>
    </table>

    <input type="submit" value="login" />
    <input type="hidden" name="next" value="{{ next }}" />
  </form>

{% endblock %}

core/templates/core/profile.html
{% extends "core/base.html" %}

{% load staticfiles %}

{% block title %}
Profile Page
{% endblock %}

{% block content %}

  {% if user.is_authenticated %}
    {{ user.email }}'s profile 
  {% endif %}
{% endblock %}