core/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'core.views.index', name='index'),
    url(r'^home/$', 'core.views.home', name='home'),
    url(r'^profile/$', 'core.views.profile', name='profile'),
    url(r'^about/$', 'core.views.about', name='about'),
    url(r'^invite/team/members/$', 'core.views.invite_team_members', name='invite_team_members'),
    url(r'^mark/paid/(?P<payment_id>\d+)/$', 'core.views.mark_paid', name='mark_paid'),
    url(r'^payments/$', 'core.views.payments', name='payments'),
    url(r'^expense/add/$', 'core.views.add_expense', name='add_expense'),
    url(r'^change/group/name/(?P<group_id>\d+)/$', 'core.views.change_group_name', name='change_group_name'),
)

expense/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
  # Examples:
  url(r'^$', 'expense.views.index', name='index'),
  url(r'^add/$', 'expense.views.add_expense', name='add_expense'),
  url(r'^contributor/mixin/add/$', 'expense.views.add_contributor_mixin', name='add_contributor_mixin'),
  url(r'^contributions/$', 'expense.views.contributions', name='contributions'),
  url(r'^requested/contributions/$', 'expense.views.requested_contributions', name='requested_contributions'),
  url(r'^teammembers/add/$', 'expense.views.add_teammembers', name='add_teammembers'),
  url(r'^teammember/mixin/add/$', 'expense.views.add_teammember_mixin', name='add_teammember_mixin'),
  url(r'^bankcard/add/$', 'expense.views.add_bank_card', name='add_bank_card'),
  url(r'^multiple/add/$', 'expense.views.add_multiple_expenses', name='add_multiple_expenses'),
  url(r'^contribute/(?P<contribution_id>\d+)/$', 'expense.views.contribute_to_contribution', name='contribute_to_contribution'),
  url(r'^decline/(?P<contribution_id>\d+)/$', 'expense.views.decline_contribution', name='decline_contribution'),
)

familybridge/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.contrib import admin
from core.forms import TopLoginForm, FrontSignUpForm

admin.autodiscover()

urlpatterns = patterns('',
  # Examples:
  #url(r'^account/password_reset/', 'django.contrib.auth.views.password_reset', {'html_email_template_name': 'registration/password_reset_html_email.html'}),
  url(r'^account/', include('django.contrib.auth.urls')),
  url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'core/index.html',
                                                      'authentication_form': TopLoginForm,
                                                      'extra_context': {'signup_form': FrontSignUpForm()}
                                                      }, name='login'),
  url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout'),
  url(r'^signup/$', 'core.views.sign_up', name='signup'),
  # url(r'^blog/', include('blog.urls')),

  url(r'^admin/', include(admin.site.urls)),

  url(r'^mobile/', include('mobile.urls', namespace='mobile')),
  url(r'^expense/', include('expense.urls', namespace='expense')),
  url(r'^settings/', include('setup.urls', namespace='setup')),
  url(r'^support/', include('support.urls', namespace='support')),
  url(r'^', include('core.urls', namespace='core')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + staticfiles_urlpatterns()

expense/models.py
from django.db import models
from django.conf import settings


class Expense(models.Model):
  owner = models.ForeignKey(settings.AUTH_USER_MODEL)
  title = models.CharField(max_length=64)
  description = models.CharField(max_length=256, blank=True, null=True)
  amount = models.DecimalField(max_digits=16, decimal_places=2)

  CATEGORY_CHOICES = (
    (0, 'Living Expense'),
    (1, 'Housing'),
    (2, 'Food'),
    (3, 'Medication'),
    (4, 'Health'),
    (5, 'Recreation'),
    (6, 'Other'),
  )

  category = models.IntegerField(choices=CATEGORY_CHOICES)
  date = models.DateField()
  contribution_requested = models.BooleanField(default=False)

  timestamp = models.DateTimeField(auto_now_add=True)  
  updated = models.DateTimeField(auto_now=True)

  def contributors(self):
    return self.contribution_set.all()


class Contribution(models.Model):
  contributor = models.ForeignKey(settings.AUTH_USER_MODEL)
  expense = models.ForeignKey(Expense)
  percentage = models.IntegerField(default=0)
  # for easy calculation without joining
  amount = models.DecimalField(max_digits=16, decimal_places=2)

  # if the user confirmed contribution
  contributed = models.DateTimeField(blank=True, null=True)
  # if the user was reminded to contribute
  last_reminded = models.DateTimeField(blank=True, null=True)
  # if payment has been fully reconciled
  reconciled = models.DateTimeField(blank=True, null=True)

  timestamp = models.DateTimeField(auto_now_add=True)  
  updated = models.DateTimeField(auto_now=True)

  def update_contribution(self):
    self.amount = self.expense.amount * float(percentage) / 100.0
    self.save()

  def feed_str(self):
    owner = self.expense.owner
    amount = self.expense.amount
    title = self.expense.title
    feed_str = "{0} spent ${1} on {2}.".format(owner.first_name, amount, title)
    return feed_str

  def contribute_str(self):
    contribute_str = "Contribute ${0} ({1}%)".format(self.amount, self.percentage)
    return contribute_str

  def contributed_exists(self):
    return self.expense.contribution_set.filter(contributed__isnull=False).exists()

  def contributed_users(self):
    return self.expense.contribution_set.filter(contributed__isnull=False)

  def requested_exists(self):
    return self.expense.contribution_set.filter(contributed__isnull=True).exists()

  def requested_users(self):
    """
      People who have been requested but not yet contributed
    """
    return self.expense.contribution_set.filter(contributed__isnull=True)

expense/forms.py
from django import forms
from expense.models import Expense, Contribution
from core.models import EmailUser

class AddExpenseForm(forms.ModelForm):

  class Meta:
    model = Expense

  def __init__(self, *args, **kwargs):
    super(AddExpenseForm, self).__init__(*args, **kwargs)

    signup_field_width = 370

    self.fields['date'].widget.attrs['class'] = 'form-control'
    #self.fields['first_name'].widget.attrs['style'] = 'width:%dpx;' % (signup_field_width/2)
    self.fields['date'].widget.attrs['placeholder'] = 'MM/DD/YYYY'
    self.fields['date'].widget.attrs['type'] = 'date'
    self.fields['amount'].widget.attrs['class'] = 'form-control'
    #self.fields['last_name'].widget.attrs['style'] = 'width:%dpx;' % (signup_field_width/2)
    self.fields['amount'].widget.attrs['placeholder'] = 'Amount'
    self.fields['title'].widget.attrs['class'] = 'form-control'
    #self.fields['email'].widget.attrs['style'] = 'width:%dpx;' % signup_field_width
    self.fields['title'].widget.attrs['placeholder'] = 'Title'

    self.fields['description'].widget.attrs['class'] = 'form-control'
    #self.fields['password1'].widget.attrs['style'] = 'width:%dpx;' % signup_field_width
    self.fields['description'].widget.attrs['placeholder'] = 'Description'
    self.fields['category'].widget.attrs['class'] = 'form-control'
    #self.fields['password2'].widget.attrs['style'] = 'width:%dpx;' % signup_field_width
    self.fields['category'].widget.attrs['placeholder'] = 'Category'


PERCENTAGE_CHOICES = (
  (0, '------'),
  (10, '10%'),
  (20, '20%'),
  (30, '30%'),
  (40, '40%'),
  (50, '50%'),
  (60, '60%'),
  (70, '70%'),
  (80, '80%'),
  (90, '90%'),
  (100, '100%'),
)

class ContributeForm(forms.ModelForm):

  class Meta:
    model = Contribution


class AddContributorForm(forms.ModelForm):

  percentage = forms.ChoiceField(widget=forms.Select, choices=PERCENTAGE_CHOICES)

  class Meta:
    model = Contribution
    fields = ['contributor', 'percentage']

  def __init__(self, *args, **kwargs):
    super(AddContributorForm, self).__init__(*args, **kwargs)

    self.fields['contributor'].widget.attrs['class'] = 'form-control'
    self.fields['percentage'].widget.attrs['class'] = 'form-control'


class AddTeamMemberForm(forms.ModelForm):

  class Meta:
    model = EmailUser
    fields = ['first_name', 'last_name', 'email']

  def __init__(self, *args, **kwargs):
    super(AddTeamMemberForm, self).__init__(*args, **kwargs)

    self.fields['first_name'].widget.attrs['class'] = 'form-control'
    self.fields['first_name'].widget.attrs['placeholder'] = 'First Name'
    self.fields['last_name'].widget.attrs['class'] = 'form-control'
    self.fields['last_name'].widget.attrs['placeholder'] = 'Last Name'
    self.fields['email'].widget.attrs['class'] = 'form-control'
    self.fields['email'].widget.attrs['placeholder'] = 'E-mail'

expense/views.py
from django.shortcuts import render
from django.template.loader import render_to_string
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.http import StreamingHttpResponse
from django.db.models import Sum
from django.forms.formsets import formset_factory

import json

from expense.models import Expense, Contribution
from core.models import EmailUser
from expense.forms import AddTeamMemberForm, AddExpenseForm, AddContributorForm



# Create your views here.

@login_required
def index(request):
  """
    Shows the list/history of expenses

    Allow filter by month and by people 
  """ 
  data = {}

  data["current_page"] = "expense"

  data["expenses"] = Expense.objects.all()

  agg = Expense.objects.aggregate(total_expenses=Sum('amount'))
  data["total_expenses"] = agg['total_expenses']
  return render(request, "expense/index.html", data)


@login_required
def contributions(request):
  data = {}

  data["current_page"] = "contribute"

  return render(request, "expense/contributions.html", data)

@login_required
def add_expense(request):
  data = {}

  data["current_page"] = "expense"
  return render(request, "expense/index.html", data)

@login_required
def add_teammembers(request):
  """
    Shows view for adding team members and processes new teammember add
  """
  data = {}

  data["current_page"] = "home"

  AddTeamMemberFormset = formset_factory(AddTeamMemberForm, can_delete=True)
  data["teammember_formset"] = AddTeamMemberFormset()
  return render(request, "expense/add_contributors.html", data)

@login_required
def add_teammember_mixin(request):
  sub_data = {}
  data = {}

  u = request.user
  #users = EmailUser.objects.filter(groups__in=u.groups.all())
  new_form_id = int(request.GET['new_form_id'])
  sub_data["new_form_id"] = new_form_id
  data["teammember_form"] = render_to_string("expense/add_teammember_mixin.html", sub_data)
  data["result"] = 1
  return StreamingHttpResponse(json.dumps(data), content_type="application/json")

@login_required
def add_contributor_mixin(request):
  sub_data = {}
  data = {}

  u = request.user
  #users = EmailUser.objects.filter(groups__in=u.groups.all())
  users = EmailUser.objects.all()
  new_form_id = int(request.GET['new_form_id'])
  if new_form_id < users.count():
    sub_data["new_form_id"] = new_form_id
    sub_data["users"] = users
    data["contributor_form"] = render_to_string("expense/add_contributor_mixin.html", sub_data)
    data["result"] = 1
  else:
    data["result"] = 0
  return StreamingHttpResponse(json.dumps(data), content_type="application/json")

@login_required
def add_bank_card(request):
  data = {}

  data["current_page"] = "expense"
  return render(request, "expense/add_bank_card.html", data)


@login_required
def add_multiple_expenses(request):
  data = {}

  data["current_page"] = "expense"

  AddExpenseFormset = formset_factory(AddExpenseForm, can_delete=True, extra=4, max_num=4)
  data["add_expense_formset"] = AddExpenseFormset()

  AddContributorsFormset = formset_factory(AddContributorForm, can_delete=True)
  data["contributors_formset"] = AddContributorsFormset()

  return render(request, "expense/add_multiple_expenses.html", data)


@login_required
def comment_on_feed(request):
  data = {}

  return StreamingHttpResponse(json.dumps(data), content_type="application/json") 

@login_required
def close_feed(request):
  data = {}

  return StreamingHttpResponse(json.dumps(data), content_type="application/json")

@login_required
def contribute(request):
  """
    @param contribution_id
    @param percentage: only if optional percentage
  """
  data = {}  

  return StreamingHttpResponse(json.dumps(data), content_type="application/json")

@login_required
def requested_contributions(request):

  data = {}

  u = request.user

  data["current_page"] = "contribute"

  # just top 4
  data["contributions"] = Contribution.objects.filter(contributor=u)[:4]
  return render(request, "expense/requested_contributions.html", data)

@login_required
def contribute_to_contribution(request):

  data = {}
  u = request.user
  return render(request, "expense/requested_contributions.html", data)

@login_required
def decline_contribution(request):

  data = {}
  u = request.user
  return render(request, "expense/requested_contributions.html", data)

expense/templates/expense/add_contributor_mixin.html
<div class="form-group">
  <div class="row">
    <div class="reduce-right-padding-0 col-sm-5 col-lg-5">
      <select class="form-control" id="id_form-{{ new_form_id }}-contributor" name="form-{{ new_form_id }}-contributor">
        <option value="" selected="selected">---------</option>
        {% for u in users %}
          <option value="{{ u.id }}">{{ u.email }}</option>
        {% endfor %}
      </select>
    </div>
    <div class="reduce-left-padding-10 col-sm-6 col-lg-6">
      <select class="form-control" id="id_form-{{ new_form_id }}-percentage" name="form-{{ new_form_id }}-percentage">
        <option value="0">------</option>
        <option value="10">10%</option>
        <option value="20">20%</option>
        <option value="30">30%</option>
        <option value="40">40%</option>
        <option value="50">50%</option>
        <option value="60">60%</option>
        <option value="70">70%</option>
        <option value="80">80%</option>
        <option value="90">90%</option>
        <option value="100">100%</option>
      </select>                 
    </div>
  </div>
</div>

expense/templates/expense/add_contributors.html
{% extends "core/base.html" %}

{% block content %}

<div class="col-sm-3 col-lg-3">
  <a href="{% url 'expense:add_teammembers' %}" class="btn btn-info btn-lg btn-block">Add Contributors</a>
  <div class="questions-call">
    Have a question? Need help? Give us a call: 1-800-FAMBRIDGE
  </div>
</div>

<div class="col-sm-9 col-lg-9">
  <div class="add-contributors grey-area">
    <h3>Add Care Contributors</h3>
    <p>
    Let's get the rest of your care team onboard.  To add contributors, share Family Bridge with fellow Care Contributors and we'll send them an email inviting them to join your Family Bridge.
    </p>
    <p>
      To:
    </p>
    <form class="form-inline" role="form" method="POST" action="{% url 'expense:add_teammembers' %}">
      {% csrf_token %}
      {{ teammember_formset.management_form }}
      <div id="teammember-edit-list">
        {% for invite_form in teammember_formset %}
          <div class="row">
            {{ invite_form.id }}
            <div class="form-group col-sm-3 col-lg-3">
              {{ invite_form.first_name }}
            </div>
            <div class="form-group col-sm-3 col-lg-3">
              {{ invite_form.last_name }}
            </div>           
            <div class="form-group col-sm-3 col-lg-3">
              {{ invite_form.email }}
            </div>           
            {% if not forloop.first %}
            <div class="form-group col-sm-3 col-lg-3">
              {% if teammember_formset.can_delete %}
                <i class="icon-remove icon-2x"></i>
              {% endif %}
            </div>
            {% endif %}
          </div>
        {% endfor %}
      </div>

      <div class="row">
        <div class="form-group col-sm-12 col-lg-12">
          <button id="add-teammember" class="btn btn-default"><i class="glyphicon glyphicon-plus"></i>Add Contributor</button>
        </div>
      </div>

      <div class="pull-right">
        <input type="reset" class="btn btn-default" value="Cancel">
        <input type="submit" class="btn btn-success" value="Send">
      </div>
    </form>
  </div>
</div>
{% endblock %}

{% block additional_scripts %}
<script type="text/javascript">
    // for handling additional contributors, allow adding contributor up to number
    // of members in the group
    $("#add-teammember").click(function () {
      var total_forms = parseInt($("#id_form-TOTAL_FORMS").attr('value'));
      $("#id_form-TOTAL_FORMS").attr('value', total_forms+1);
      // add new forms
      $.get("{% url 'expense:add_teammember_mixin' %}", {new_form_id: total_forms}, function (data) {
        if (data["result"] == 1) {
          $("#teammember-edit-list").append(data['teammember_form']);
        } else {
          return false;
        }
      });
      return false;
    });
  </script>
{% endblock %}

expense/templates/expense/add_multiple_expenses.html
{% extends "core/base.html" %}

{% block content %}

<form method="POST" action="{% url 'expense:add_multiple_expenses' %}">
  <div class="row">
    <div class="grey-area">
      <div class="col-sm-12 col-lg-12">
        <h4>Upload Multiple Expenses</h4>
      </div>
      <form action="" method="POST">
        {% csrf_token %}
        {{ add_expense_formset.management_form }}

        {% for add_expense_form in add_expense_formset %}
        <div class="col-sm-3 col-lg-3">
          <div class="green-area">
            <div class="form-group">
              <input class="form-control" id="id_date" name="date" type="date">
            </div>

            <div class="form-group">
              <div class="row">
                <div class="reduce-right-padding-0 col-sm-9 col-lg-9">
                  {{ add_expense_form.amount }}
                </div>
                <div class="reduce-left-padding-0 reduce-right-padding-0 align-right col-sm-2 col-lg-2">
                  <button class="btn btn-default"><i class="icon-paper-clip"></i></button>
                </div>
              </div>
            </div>       

            <div class="form-group">
              {{ add_expense_form.title }}
            </div>
            <div class="form-group">
              {{ add_expense_form.description }}
            </div>
            <div class="form-group">
              {{ add_expense_form.category }}
            </div>

            {{ contributors_formset.management_form }}
            <div id="contributor-list">
              {% for add_contributor_form in contributors_formset %}
                {{ add_contributor_form.id }}
                <div class="form-group">
                  <div class="row">
                    <div class="reduce-right-padding-0 col-sm-5 col-lg-5">
                      {{ add_contributor_form.contributor }}
                    </div>
                    {% if contributors_formset.can_delete %}
                      <div class="reduce-left-padding-10 reduce-right-padding-0 col-sm-5 col-lg-5">
                        {{ add_contributor_form.percentage }}
                      </div>
                      <div class="reduce-left-padding-10 col-sm-1 col-lg-1">
                        <i class="icon-remove icon-2x"></i>
                      </div>
                    {% else %}
                      <div class="reduce-left-padding-10 col-sm-6 col-lg-6">
                        {{ add_contributor_form.percentage }}
                      </div>
                    {% endif %}
                  </div>
                </div>
              {% endfor %}
            </div>

            <div class="form-group">
              <button type="button" id="add-contributor" class="btn btn-default btn-block"><i class="glyphicon-pluslyphicon glyphicon-plus"></i> Add Contributor</button>
            </div>          
          </div> <!-- green-area -->
        </div>

        {% endfor %}
      </form>
    </div>
  </div>

  <p></p>
  <div class="row">
  <div class="pull-right">
    <a href="{% url 'expense:index' %}" class="btn btn-default">Return to Expenses</a>
    <input type="submit" class="btn btn-success" name="Save" value="Save Expenses">
  </div>
  </div>
</form>
{% endblock %}

{% block additional_scripts %}

{% endblock %}

expense/templates/expense/add_teammember_mixin.html
<div class="row">
  <div class="form-group col-sm-3 col-lg-3">
    <input class="form-control" id="id_form-{{ new_form_id }}-first_name" maxlength="36" name="form-{{ new_form_id }}-first_name" placeholder="First Name" type="text">
  </div>
  <div class="form-group col-sm-3 col-lg-3">
    <input class="form-control" id="id_form-{{ new_form_id }}-last_name" maxlength="36" name="form-{{ new_form_id }}-last_name" placeholder="Last Name" type="text">
  </div>
  <div class="form-group col-sm-3 col-lg-3">
    <input class="form-control" id="id_form-{{ new_form_id }}-email" maxlength="255" name="form-{{ new_form_id }}-email" placeholder="E-mail" type="email">
  </div>
</div>

expense/templates/expense/contributions.html
{% extends "core/base.html" %}

{% load thumbnail %}

{% block content %}
<div class="row grey-area">
  <div class="col-sm-12 col-lg-12">
    <h4>Current Care Balances</h4>

    {% for owe in care_balances %}
    {% endfor %}
    <div class="row">
      <div class="col-sm-3 col-lg-3">
        {% thumbnail c.contributor.pic "100x100" as im %}
          <img src="{{ im.url }}" width="{{ im.x }}" height="{{ im.y }}">
        {% empty %}
          <div class="pic-empty-large" style="background-color:{{ c.contributor.background_color }};">
            {{ c.contributor.first_name_initial }}
          </div>
        {% endthumbnail %}      
      </div>
      <div class="col-sm-5 col-lg-5">
        <div class="row">
          <div class="col-sm-6 col-lg-6">
            You owe Jeff:
          </div>
          <div class="col-sm-6 col-lg-6 pull-right">
            $230.55
          </div>
        </div>
        <div class="row">
          <div class="col-sm-6 col-lg-6">
            You owe Jeff:
          </div>
          <div class="col-sm-6 col-lg-6 pull-right">
            $230.55
          </div>
        </div>
        <div class="row">
          <div class="col-sm-6 col-lg-6">
            You owe Jeff:
          </div>
          <div class="col-sm-6 col-lg-6 pull-right">
            $230.55
          </div>
        </div>
      </div>
      <div class="col-sm-4 col-lg-4">
        <div class="btn btn-lg btn-success">
          Contribute to<br>Jeff's Expenses
        </div>
      </div>
    </div>
  </div>
</div>
</div>
<p></p>
<div class="row">
  <div class="text-center">
    <a href="{% url 'expense:requested_contributions' %}" class="btn btn-lg btn-info">Your Requested Contributions</a>
  </div>
</div>
{% endblock %}

{% block footer %}
{% endblock %}

expense/templates/expense/index.html
{% extends "core/base.html" %}

{% load thumbnail %}

{% block content %}
  <div class="row">
    <div class="text-center">
      <a href="{% url 'expense:add_multiple_expenses' %}" class="btn btn-success btn-lg">Add Expenses</a>
    </div>
  </div>
  <p></p>
  <div class="row">
    <div class="col-sm-12 col-lg-12">
      <div class="expense-table grey-area">
        <div class="expense-table-menu">
          <div class="col-sm-2 col-lg-2">
            <h4>Expenses</h4>
          </div>
          <div class="col-sm-2 col-lg-2">
            <div class="btn-group">
              <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                All Expenses 
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu">
                <li><a href="#">Dropdown link</a></li>
                <li><a href="#">Dropdown link</a></li>
              </ul>
            </div>
          </div>
          <div class="col-sm-2 col-lg-2">
            <div class="btn-group">
              <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                All Time 
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu">
                <li><a href="#">Dropdown link</a></li>
                <li><a href="#">Dropdown link</a></li>
              </ul>
            </div>
          </div>
          <div class="col-sm-2 col-lg-2">
            <div class="btn-group">
              <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                All Categories 
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu">
                <li><a href="#">Dropdown link</a></li>
                <li><a href="#">Dropdown link</a></li>
              </ul>
            </div>            
          </div>
          <div class="col-sm-2 col-lg-2">
            <div class="btn-group">
              <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                By All 
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu">
                <li><a href="#">Dropdown link</a></li>
                <li><a href="#">Dropdown link</a></li>
              </ul>
            </div> 
          </div>
          <div class="col-sm-2 col-lg-2">
            <div class="pull-right">
              <i class="icon-envelope icon-2x"></i>
              <i class="icon-inbox icon-2x"></i>
            </div>
          </div>
        </div>

        <table class="table table-striped">
          <thead>
            <tr>
              <th>
                <a href="">Date <i class="icon-sort-down"></i></a>
              </th>
              <th>
                <a href="">Title <i class="icon-sort-down"></i></a>
              </th>
              <th>
                <a href="">Amount <i class="icon-sort-down"></i></a>
              </th>
              <th>
                <a href="">Category <i class="icon-sort-down"></i></a>
              </th>
              <th>
                <a href="">By <i class="icon-sort-down"></i></a>
              </th>             
              <th>
                <a href="">Description <i class="icon-sort-down"></i></a>
              </th>                          
              <th>
                <a href="">Contributed <i class="icon-sort-down"></i></a>
              </th>                                        
            </tr>
          </thead>
          <tbody>
            {% for exp in expenses %}
            <tr>
              <td>
                {{ exp.date|date:"SHORT_DATE_FORMAT" }}
              </td>
              <td>
                {{ exp.title }}
              </td>
              <td>
                ${{ exp.amount|floatformat:2 }}
              </td>
              <td>
                {{ exp.get_category_display }}
              </td>
              <td>
                {% thumbnail exp.owner.pic "25x25" as im %}
                  <img src="{{ im.url }}" width="{{ im.x }}" height="{{ im.y }}">
                {% empty %}
                  <div class="pic-empty-icon" style="background-color:{{ exp.owner.background_color }};">
                    {{ exp.owner.first_name_initial }}
                  </div>
                {% endthumbnail %}
              </td>
              <td>
                {{ exp.description }}
              </td>
              <td>
                {% for c in exp.contributors %}
                  <div class="row">
                    <div class="col-sm-2 col-lg-2">
                      {% thumbnail c.contributor.pic "25x25" as im %}
                        <img src="{{ im.url }}" width="{{ im.x }}" height="{{ im.y }}">
                      {% empty %}
                        <div class="pic-empty-icon" style="background-color:{{ c.contributor.background_color }};">
                          {{ c.contributor.first_name_initial }}
                        </div>
                      {% endthumbnail %}
                    </div>
                    <div class="col-sm-8 col-lg-8">
                      {{ c.percentage }}% - ${{ c.amount|floatformat:2 }}
                    </div>
                  </div>
                {% endfor %}
              </td>          
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>  <!-- expense-table -->
    </div>
  </div>
  <p></p>
  <div class="row">
    <div class="col-sm-offset-4 col-lg-offset-4 col-sm-4 col-lg-4">
      <ul class="pagination">
        <li><a href="#">&laquo;</a></li>
        <li><a href="#">1</a></li>
        <li><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li><a href="#">4</a></li>
        <li><a href="#">5</a></li>
        <li><a href="#">&raquo;</a></li>
      </ul>
    </div>
    <div class="col-sm-3 col-lg-3 pull-right">
      Total Expenses to Date: ${{ total_expenses }}
    </div>
  </div>
{% endblock %}

{% block footer %}
{% endblock %}